name: GitHub to GitLab Mirroring
on:
  push:
    branches:
      - main

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: Clone GitHub Fork (Full History)
        uses: actions/checkout@v3
        with:
          submodules: false
          path: source
          fetch-depth: 0 # Critical: Fetch full history instead of shallow clone

      - name: Clean GitHub Workflows
        run: |
          rm -rf source/.github
          rm -rf source/.gitmodules

      - name: Push to GitLab
        run: |
          git config --global user.email "${{ secrets.GITLAB_EMAIL }}"
          git config --global user.name "CI Bot"
          cd source
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_PAT }}@git.saltrivercanyon.com/WaterPistol/distributed-llama.git
          git push gitlab --force main
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_PAT }}
